addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 70a015fd-5a5d-4b5d-9932-4a9cf998a162
after_success:
- ./df-build.sh
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  $HOME/.m2/settings.xml
branches: ''
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk7
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-campaign.public-swarm.devfactory.com/travisWebHookListener?build_id=70a015fd-5a5d-4b5d-9932-4a9cf998a162
script: mvn clean install -Dmaven.test.skip=true
# Modified by Insights Service at 2016-10-17 13:18:16.920966
